version: "3.8"

services:
  server-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
    ports:
      - "8080:8080"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  sql_data:
